### ISSUE TITLE
Convert Copper user manual to Markdown.

### ISSUE THREAD

**Issue by schwerdf** [melt-umn/copper#18]
Copper's user manual, being written in LaTeX, is not available in "online" form, but only as a downloadable PDF.

As far as I know there is nothing within the manual preventing its straightforward conversion into Markdown, which would allow it to be displayed online without eliminating the possibility of a PDF version.

**Comment by schwerdf** [comment]
A Markdown version of the user manual, generated using `pandoc` and some hand-tweaking, has now been added to the repository, although it is without a table of contents or any cross-references as `pandoc` cannot handle LaTeX labels and references.

**Comment by ericvanwyk** [comment]
Could you add a link to this from the melt webpage?   Maybe in the paragraph that mentions GitHub just above the acknowledgements.

**Comment by schwerdf** [comment]
Done. (I targeted the link to the master branch, so it will not work until I do the merge.)

Do you know of any way to generate tables-of-contents for Markdown files automatically?

**Comment by ericvanwyk** [comment]
Thanks.  I don't know how to generate tables of contents - @tedinski  do you know?

**Comment by schwerdf** [comment]
I found a Node.js tool, [markdown-toc](https://github.com/jonschlinkert/markdown-toc), that did the job. It was simpler than I thought, since it is apparently not necessary to add an anchor explicitly to each section header.
