### ISSUE TITLE
Unresolvable lexical ambiguities between ignore terminals not caught during compilation

### ISSUE THREAD

**Issue by krame505** [melt-umn/copper#33]
For example, the following minimal Silver grammar:
```
grammar ignore_conflict;

ignore terminal Foo1 'foo';
ignore terminal Foo2 'foo';

nonterminal Root;

concrete production root
top::Root ::=
{}

parser parse::Root {
  ignore_conflict;
}

function main 
IOVal<Integer> ::= args::[String] ioin::IO
{
  return ioval(print(parse("foo", "test").parseErrors, ioin), 0);
}
```
reports "No lexical ambiguities detected" when compiled, but produces the following error when run:
```
Error at line 1, column 0 in file test
         (parser state: 1; real character index: 0):
  Lexical ambiguity between tokens:
   ['foo',
    'foo']
```
For reference, here is the generated `.copper` file: [Parser_ignore_conflict_parse.copper](https://github.com/melt-umn/copper/files/2002505/Parser_ignore_conflict_parse.copper.txt)

**Comment by schwerdf** [comment]
Copper allows lexical ambiguities between terminals with identical reduce actions. This exception was erroneously being applied to terminals that have an identical _lack_ of actions (_i.e._, grammar layout).
Fixed in commit d3fcbe4.
