### ISSUE TITLE
Disambiguation classes

### ISSUE THREAD

**Issue by krame505** [melt-umn/copper#34]
This is a continuation of https://github.com/melt-umn/silver/issues/193.  
We essentially want to add a mechanism similar to disambiguation functions, except as an open set of ambiguous terminals where we don't know, at the declaration, everything that may possibly be a member of the class.  A disambiguation class should also apply for any ambiguity that is a subset of its terminals, as opposed to a fixed set of terminals.  Since the logic to select a member of the class remains the same no matter what terminals are actually in the set of potential matches, it may happen that a terminal is selected by the class that is not a potential match - in this case, a syntax error should be raised.  
Some implementation considerations:
* We are considering implementing disambiguation classes as an optional component of terminal classes, containing a piece of code to run indicating which terminal should be selected.  The copper compiler would treat any ambiguity where all terminals are members of the same terminal class containing a disambiguation expression as resolved.  
* The code corresponding to a disambiguation class would typically involve looking up the lexeme in some sort of environment to find which terminal to match, similar to the lexer hack in C (which itself would be re-implemented as a disambiguation class.)  This means that terminals must be identified in some way outside of the disambiguation class code, so the disambiguation function approach of generating an identifier corresponding to the Copper name of each terminal is not an option.  One possibility is to have the code evaluate to a String containing the Copper name of the chosen identifier, which would then be looked up from a generated table to find the actual BitSet index of the terminal, however this may have performance issues.  However I can't think of a better approach, such as querying the information from the parser at startup, since the code constructing the disambiguation environment would be totally independent from Copper and could potentially be used in multiple parsers generated from the same grammar.  

Any other thoughts/comments?

**Comment by schwerdf** [comment]
To clarify, what you are looking for is
1. a special class of disambiguation function that is able to resolve any ambiguity that is a subset of its membership; and
1. a way to reference Copper terminals that is consistent across all semantic actions, to implement lookup tables for use in these disambiguation functions?

**Comment by krame505** [comment]
Yes, that is correct - but additionally, this consistent way of referencing Copper terminals must be possible outside of any Copper action code (e.g. a Silver collection function that constructs the initial lookup table.)

**Comment by schwerdf** [comment]
Supporting the "disambiguation classes" would be a matter of adding a new boolean attribute on disambiguation functions such as `appliesToSubsets`, making a small change to the generation of the dispatch methods for disambiguation actions, and adding extra checks to make sure that there will never be two disambiguation functions matching the same ambiguity. Alternatively, you could use Silver to generate the same disambiguation function for every applicable subset of the membership of the "disambiguation class," which would have the same effect.

For terminal references, each Copper parser using the `SingleDFAEngine` has a public enum, `Terminals`, mapping terminal names to internal indices, which I think would suit your purposes for building the lookup tables: where you would reference, say, `TypeName_t` in a semantic action, you would use `Terminals.TypeName_t.num()` in external Java. This would introduce the assumption that any Copper parser used with these lookup tables has such an enum, so an additional abstraction barrier may be necessary if you are going to use it with, _e.g._, Kevin's `ParserFragmentEngine`.

**Comment by krame505** [comment]
To be clear, one way that disambiguation classes would differ from disambiguation functions is that we don't know at the definition of the class what terminals are members of the class.  I suppose we could statically generate this set with Silver by seeing what terminals are members of a lexer class, but this might pose issues in the future for runtime composition.  

The issue with the approach of getting the terminal indices from the `Terminals` enum is that the code used to construct the lookup table would exist outside of parser action blocks, and thus the enum wouldn't be directly accessible.  We may even have multiple generated parsers using some of the same sub-grammars, resulting in some terminals having different indices in different parsers.  This is why I mentioned using strings here, which could potentially use reflection to access the enum constants, although that seems inefficient.

**Comment by schwerdf** [comment]
Introducing host-language disambiguation functions or terminal classes whose membership could potentially be modified by extensions would also pose issues for runtime composition, so you probably do not need to worry too much about that.

For the `Terminals` enum, what do you mean by "outside of parser action blocks"? I assumed you meant the parser initialization code or class preamble -- is this lookup table something that would be built in Silver before Copper even starts to run?

**Comment by krame505** [comment]
> Introducing host-language disambiguation functions or terminal classes whose membership could potentially be modified by extensions would also pose issues for runtime composition, so you probably do not need to worry too much about that.

Don't we *already* have terminal classes where extensions can introduce additional members?  e.g. a `Keyword` class that dominates identifiers, where extensions can introduce new `Keyword` marking terminals.  How is this case be different?  

> For the `Terminals` enum, what do you mean by "outside of parser action blocks"? I assumed you meant the parser initialization code or class preamble -- is this lookup table something that would be built in Silver before Copper even starts to run?

Ideally, yes, involving a Silver collection production attribute in a seperate function - but if this is really a major issue, then I suppose constructing this table could be done during parser initialization.

**Comment by krame505** [comment]
After discussing this a bit more with Eric we decided that it is probably reasonable to limit the use of these "terminal identifier literals" to inside parser action blocks.  Also your suggested approach of introducing an `appliesToSubsets` attribute on disambiguation functions (statically generating the set of terminals in the class) is probably a good place to start with implementing this, although it would also require adding error checking to disambiguation functions for the case were we return a terminal not in the particular subset we are handling.  
Eric mentioned that you were interested in meeting in person to better understand and work out some of the details here - I agree this would be a good idea as well.

**Comment by ericvanwyk** [comment]
@schwerdf - would meeting next Monday or Tuesday afternoon sometime work for you?

**Comment by schwerdf** [comment]
After further discussion, it was determined to go ahead with the `appliesToSubsets` attribute. To handle overlapping disambiguation-function membership, preference will be given to those disambiguation functions that do _not_ apply to subsets, and all those that do must have disjoint member sets.

**Comment by krame505** [comment]
Tasks to complete for this feature, copied from August's email:

- [ ] Add a new flag 'appliesToSubsets' to disambiguation function objects.  (This is already done, on the 'feature/disambiguate_subsets' branch.)

- [ ] Add a new version ("0.9") of the XML skin schema and parser. This is largely a matter of duplicating the now-frozen 0.8 version.

- [ ] Update the 0.9 schema and parser to handle a 'appliesToSubsets' attribute on disambiguation functions.

- [ ] Add a new "checker" in the 'compiletime.checker' package that will verify that all disambiguation functions with the 'appliesToSubsets' flag set have disjoint member sets.
  - This should also check that no two disambiguation functions have the same member set.
  - Also possibly add a new error-message type in the 'compiletime.logging.message' package so the checker can make structured reports of its findings.

- [ ] Alter the code generation for the 'runDisambiguationAction' method in parser classes. This currently generates an if statement for each disambiguation function, of the form
```java
if (match.terms.equals(disambiguationGroups[<<i>>]))
  return disambiguate_<<i>>(lexeme);
```
   - These will need to be reordered, with the statements for all the non-'appliesToSubsets' functions going before any statement for a 'appliesToSubsets' function.
   - For the 'appliesToSubsets' functions, 'match.terms' need only be subset of the member set and not equal to it.
   - A value of -1 must be returned if the return value from `disambiguate_<<i>>` is not in 'match.terms'. This must now be checked for explicitly.

- [ ] Finally, dispense with any assumption that 'runDisambiguationAction' never returns -1. The appropriate reaction in this case is to throw a syntax error.

**Comment by krame505** [comment]
August, did I miss anything with creating the v0.9 XML skin schema/parser?  Thanks.

**Comment by schwerdf** [comment]
The copy looks good -- now you just need to add the bits in `VersionSpecificXMLSkinParser` and the master schema that couple it to the rest of the parsing harness.

**Comment by krame505** [comment]
Ok, hopefully I got everything now?  I didn't change the tests using the 0.8 schema, will we want to update the tests to use the new schema version, or do we want to just leave them using 0.8 and only add future tests against 0.9?

**Comment by schwerdf** [comment]
That looks like everything. The tests can stay as-is.

**Comment by krame505** [comment]
Hi August, I think I have finished the checker for disambiguation function conflicts.  Could you take a look when you get a chance?

**Comment by krame505** [comment]
Since the Copper side of this feature is now finished, I am closing this issue.  Future discussion of the Silver use of this feature can be in https://github.com/melt-umn/silver/issues/193.
