### ISSUE TITLE
Allow shiftable set to be accessed from disambiguation functions applicable to subsets

### ISSUE THREAD

**Issue by krame505** [melt-umn/copper#38]
Currently in disambiguation functions that are applicable to subsets (we really need to come up with a shorter name...) there is no way of knowing what subset is actually being disambiguated, so a particular lexeme must always disambiguate to the same terminal regardless of what is permitted, thus effectively losing some of the benefits of context awareness in parsing.  
For example in ableC, we are using a disambiguation function applicable to subsets for identifier-like terminals (e.g. types and templated names.)  In ambiguities where e.g. a regular identifier or template identifier is permitted, we can check a context parser attribute to find that the name has been previously defined as a template function, perhaps as a forward declaration.  However, later on in the actual definition of the function, the same name appears in an ambiguity between an identifier and a type name.  Since the name isn't a type, and a template name isn't allowed at this point, the proper thing to do here is to default to parsing the name as an identifier, but since we don't have access in the disambiguation class to the shiftable set, this isn't possible.  
I propose making the shiftable bit set from `match.terms` available as a new parameter to functions generated as disambiguation functions applicable to subsets.  Thoughts?

**Comment by krame505** [comment]
> Should it be an invariant that disambiguation functions do not return terminals that do not have their shiftable bit set? 

Generally, yes, but there are some cases when this doesn't hold and we want a syntax error.  For example, when parsing a type expression and only a `TypeName_t` or `TemplateTypeName_t` are permitted, but the matched, ambiguous lexeme is in the context as an `Identifier_t`.  Here the disambiguation function would still return an `Identifier_t`, which would yield a syntax error as expected.  

>  Is this the same as the terminal being in the set of valid lookahead?

The shiftable set is always a subset of the set of valid lookahead, containing only those lookahead terminals that actually matched.

**Comment by ericvanwyk** [comment]
Ok, got it re. shiftable sets and for your example, returning ``Identifier_t`` makes sense.

Are there cases when no terminal should be returned?  Some situation when a lexical error would be the right thing?

**Comment by krame505** [comment]
Conceivably, yes - but for now the easiest way of raising a lexical error is to just return a terminal that is not shiftable.

**Comment by schwerdf** [comment]
> This makes sense.

I disagree. These subset-applying disambiguation functions are essentially syntactic sugar for handling classes of ambiguities that need the _same_ disambiguation behavior. When different lexical ambiguities need _different_ disambiguation behavior, cramming it all into the same disambiguation function is not the best way to go.

I think we need to take a closer look at how to handle disambiguation functions with overlapping membership. Mandating that subset-applying disambiguation functions all have disjoint membership does prevent clashes when merging extensions, but as we see here (and in issue #37) it may prove overly restrictive.

**Comment by schwerdf** [comment]
The connection I saw with #37 is that if we were to allow overlapping membership, _with_ some automatic way of resolving the resulting conflicts, then the disambiguation function that you now have to put in the host could potentially be split into two -- one with only host terminals, to be put in the host grammar, and one including the extension terminals, to be put in the extension.

This would resolve the issue of different extensions specifying disambiguation functions with member sets that share common subsets of host terminals. As it currently stands in Copper, if one extension specifies a disambiguation function on `{H1, H2, E1}` and another on `{H1,H2,E2}`, then if the extensions are composed using the composition operation on which the MDA is based, you would have a conflict with two disambiguation functions on `{H1,H2}`.

But if Silver is already resolving these conflicts in a different way, we just need to make this explicit in the Copper spec.

**Comment by krame505** [comment]
I understand how that could avoid issues with the MDA.  However the problem with that approach is that since we are writing these disambiguation functions for marking terminals, composing those two extensions could create the ambiguity `{H1, H2, E1, E2}` which would be covered by neither function.  The original idea behind disambiguation classes was to generate all potentially-needed disambiguation functions at composition time, and subset-applicable disambiguation functions were an optimization to avoid writing all the functions manually.  So I still don't quite see how allowing overlapping membership would be useful in solving this issue.

**Comment by schwerdf** [comment]
As I said, I was making an erroneous assumption about how these disambiguation functions were being composed. Since Silver is treating them as "glue code" that is not composed in the usual way, a better way to resolve issue #37 is just to represent them in Copper explicitly _as_ glue code, which can then be exempted from the rule against extension constructs in host grammars.

As to this issue, it goes somewhat against the ideal of fully declarative grammars, so I am not completely comfortable with it, but since Silver is using it in a controlled manner (and since it only applies to disambiguation functions) it is not a serious loss.
